import * as NBALogos from 'react-nba-logos';

const teams = {
    "sixers": NBALogos.PHI,
    "PHI": NBALogos.PHI,
    "blazers": NBALogos.POR,
    "POR": NBALogos.POR,
    "bucks": NBALogos.MIL,
    "MIL": NBALogos.MIL,
    "cavaliers": NBALogos.CLE,
    "CLE": NBALogos.CLE,
    "celtics": NBALogos.BOS,
    "BOS": NBALogos.BOS,
    "clippers": NBALogos.LAC,
    "LAC": NBALogos.LAC,
    "grizzlies": NBALogos.MEM,
    "MEM": NBALogos.MEM,
    "hawks": NBALogos.ATL,
    "ATL": NBALogos.ATL,
    "heat": NBALogos.MIA,
    "MIA": NBALogos.MIA,
    "hornets": NBALogos.CHA,
    "CHO": NBALogos.CHA,
    "jazz": NBALogos.UTA,
    "UTA": NBALogos.UTA,
    "kings": NBALogos.SAC,
    "SAC": NBALogos.SAC,
    "knicks": NBALogos.NYK,
    "NYK": NBALogos.NYK,
    "lakers": NBALogos.LAL,
    "LAL": NBALogos.LAL,
    "magic": NBALogos.ORL,
    "ORL": NBALogos.ORL,
    "mavericks": NBALogos.DAL,
    "DAL": NBALogos.DAL,
    "nets": NBALogos.BKN,
    "BKN": NBALogos.BKN,
    "nuggets": NBALogos.DEN,
    "DEN": NBALogos.DEN,
    "pacers": NBALogos.IND,
    "IND": NBALogos.IND,
    "pelicans": NBALogos.NOP,
    "NOP": NBALogos.NOP,
    "pistons": NBALogos.DET,
    "DET": NBALogos.DET,
    "raptors": NBALogos.TOR,
    "TOR": NBALogos.TOR,
    "rockets": NBALogos.HOU,
    "HOU": NBALogos.HOU,
    "spurs": NBALogos.SAS,
    "SAS": NBALogos.SAS,
    "suns": NBALogos.PHX,
    "PHO": NBALogos.PHX,
    "thunder": NBALogos.OKC,
    "OKC": NBALogos.OKC,
    "timberwolves": NBALogos.MIN,
    "MIN": NBALogos.MIN,
    "warriors": NBALogos.GSW,
    "GSW": NBALogos.GSW,
    "wizards": NBALogos.WAS,
    "WAS": NBALogos.WAS,
};

export default teams;